### PR TITLE
add about page

### LINKED ISSUE #595: We need an about page for certification
It should be a jinja template where Tim can add extended content.

-[ ] Content should be translatable
-[ ] there should be a link to the about page on the new certification organisation registration page.

### PR DESCRIPTION
**Pull request by ann26**
fix #595 

Static:
screenshot from 2017-10-20 18-16-18
screenshot from 2017-10-20 18-21-25

gif:
peek 2017-10-20 18-22

about page icon on the create organisation page:
screenshot from 2017-10-20 19-37-03

### CODE REVIEW

**Comment by timlinux** [comment]
Hi @ann26 this looks good. Can you add between the form heading and the first form widget (for name) this text:

"Click the (i) icon for details on how the certification programme works."

**Comment by ann26** [comment]
ok @timlinux

**Comment by ann26** [comment]
update @timlinux 
screenshot from 2017-10-24 15-24-49

**Comment by timlinux** [comment]
Lovely thanks @ann26

**Pull request merged**
