### PR TITLE
Adding sponsor app to projecta

### PR DESCRIPTION
**Pull request by rischanlab**
Refer to Issue #48 
See the comments on that issue. 

thanks

### CODE REVIEW

**Comment by timlinux** [comment]
Hi @rischanlab 

Great to see you building this. Here are some comments:

* The Sponsors should be project specific. So users in project a should not be able to reference a sponsor in project b.
* I think we should separate amount, start and end of sponsorship from the sponsor itself so that each year when a sponsorship is renewed we do not need to re-enter everything. We also don't want to change previous sponsorship periods, so it will be better to separate them.
* Just a style note that the first line of a doctoring should be less that the 80 char line wrap, terminated by a full stop and followed by a linefeed. So:

```
This is a doc string first line that is too long because it wraps over to the next line and is not separated out from follow on content.
```

```
This is a doc string first line that is fine because it does not wrap.

This is an acceptable way to add more detail to your docstring.
```

* We should add an admin interface for sponsors.

* I didn't check carefully, but we want to list out the sponsors at the top of each version see e.g. the 2.12 release of QGIS for an example.
* I also didn't check carefully but please confirm that we have a separate table with the sponsorship levels (bronze, gold etc.) and that it supports adding an image to represent that level.

I will test it out here and add further comments as needed.

**Comment by rischanlab** [comment]
Hi @timlinux 
* First, I think I did it in this PR, Just see the image below. 

screen shot 2015-11-05 at 8 19 46 pm

Sponsor must has reference to one project. When user want to add sponsor, he has to go to one project first ex: QGIS then he can add sponsor. 

* I'll think about this, I am looking the best way to do it. 
* About docstring in which file do you mean? I guess all of my docstring less than 79 but probably I miss to check in one or some files. 
* I've added the sponsor to the admin page. 
* `we want to list out the sponsors at the top of each version see e.g. the 2.12 release` I've seen the page that you mean but I cant find it, I also open the changelog.inasafe and changelog.linfiniti but I cant find it. 
* Hmm.. in this PR. for the `sponsor level` use static choice inside the model.

```
SPONSOR_CHOICES = (
    ('1', 'Platinum'),
    ('2', 'Gold'),
    ('3', 'Silver'),
    ('4', 'Bronze')
)

```
But you ask me to create different table for the sponsor level I'll do it but it takes time because I have to change `version`, `sponsor`, then add `sponsor level` because these three tables have references each others. 

Please If you have something else just tell me. 

Thanks

**Comment by rischanlab** [comment]
Hi @timlinux  I was looking some ways to handle renewed sponsorship. Then this is my propose solution. I've created `sponsor renewed` table. That table only has three coulmns `sponsor` - refer to sponsor_name in sponsor table, `start_date` and `end_date`. 

I've put the `renewed sponsor button` in list of sponsors (near button `create new sponsor`).

screen shot 2015-11-06 at 2 16 08 pm

When user click that button, the renewed sponsor form will appear like this:

screen shot 2015-11-06 at 2 16 30 pm

For the sponsor field, don't worry I've filtered based on project. 

screen shot 2015-11-06 at 2 16 45 pm

Then in the list of sponsor, I'll show the all sponsor including joining table between sponsor table and renewed_sponsor table. 

How do you think about this? 
and btw about your comment `I didn't check carefully, but we want to list out the sponsors at the top of each version see e.g. the 2.12 release of QGIS for an example.` I am still not able to find what you mean. 

thanks.

**Comment by timlinux** [comment]
>> and btw about your comment I didn't check carefully, but we want to list out the sponsors at the top of  each version see e.g. the 2.12 release of QGIS for an example. 

> I am still not able to find what you mean.

@rischanlab I am referring to e.g.

http://changelog.qgis.org/qgis/version/2.12.0/ - you see we have the sponsors list (compiled manually) at the top of the changelog:

screen shot 2015-11-06 at 22 58 18

What I would like is that we can do {{ project.sponsors_list }}  in the template for the version changelog and then a list like the above is rendered. Make sense?

**Comment by timlinux** [comment]
I'm going to merge this - we can come back and tweak in follow up PR's - thanks @rischanlab

**Pull request merged**
