### PR TITLE
Add all pending entry view

### PR DESCRIPTION
**Pull request by dimasciput**
- Added menu to open all pending entry in the project detail page
- Added test

### CODE REVIEW

**Comment by dimasciput** [comment]
Fix #310

**Comment by timlinux** [comment]
Thanks for your patch @dimasciput - it still only partially fixes the problem. It should be that when I am on a sub page for a project, I should see a menu on the right if there are pending items of any sort (entry, version etc.) With your change I see it again here:

screen shot 2016-07-01 at 12 35 38 am

The pending menu was lost on the version view with a recent update - this is quite critical as there is now no easy way to look at the queue of new items that need to be reviewed. Could you make sure that menu shows in the version view too please?

CC @nyalldawson FYI

**Comment by timlinux** [comment]
Also the new views you added are nice - but they do something different to the original. We should rename your new menu items to "All pending versions", "All pending entries" to clearly separate these new menu entries from the old one which showed just the pending entries missing for the version that the user is busy working on.

**Comment by timlinux** [comment]
Here is an example of the view we are trying to get to with the missing menu:

http://changelog.qgis.org/en/qgis/2.16.0/pending-entry/list/

**Pull request merged**
