### PR TITLE
Add project management tool

### PR DESCRIPTION
**Pull request by sumandari**
This PR refers to #1303 .

It provides checkbox to enable landing page layout

- [ ] Enable Lessons
- [ ] Enable Sustaining Members
- [ ] Enable Teams
- [ ] Enable Changelogs
- [ ] Enable Certification

image

image

### CODE REVIEW

**Comment by mbernasocchi** [comment]
Hey, @sumandari, the PR looks good to me (just from a code point of view), is there a place to try it out?
Cheers
Marco

**Comment by sumandari** [comment]
Halo @mbernasocchi, thank you for reviewing. 
This PR deployed on https://staging.changelog.kartoza.com.

Maybe it's good idea to make the Enable check box default True?
Cheers
Sumandari

image

image

**Comment by mbernasocchi** [comment]
@sumandari yes I think default on would be better

**Comment by timlinux** [comment]
Thanks @sumandari happy for you to merge this when you are ready.

**Comment by sumandari** [comment]
Thank you @timlinux @mbernasocchi, I will merge it now.

**Comment by sumandari** [comment]
@mbernasocchi @timlinux this PR has been deployed on changelog.qgis.org

**Pull request merged**
