### PR TITLE
use display block for markdown version description.

### LINKED ISSUE #630: Code markup should be a block display
Currently the code snippets in markdown look ugly because the wrap on line length:

screen shot 2017-11-14 at 15 15 48

We should using display: block for this

### PR DESCRIPTION
**Pull request by sonlinux**
Fix #630

### CODE REVIEW

**Comment by timlinux** [comment]
@sonlinux it would surprise and delight me if you provided screenshots in your PR showing the before vs after view of your change :-)

**Comment by sonlinux** [comment]
##Before
b4_markdown

##After
after_markdown


@timlinux here I have the images of of the before and after looks :-)

**Comment by timlinux** [comment]
@sonlinux hmm it still doenst give me what i am after - I think lets park if for now - I was wanting to get something more like this (where the entire block is in one group:

screen shot 2018-02-19 at 15 31 53

**Comment by sonlinux** [comment]
@timlinux is this how you meant the markdown code to be displayed , I have used some css to fix the display before. 
Here is the appearance

block_trick

**Comment by timlinux** [comment]
Ah that looks good! Thanks @sonlinux LGTM

**Pull request merged**
