### PR TITLE
change button colour and add pending details

### PR DESCRIPTION
**Pull request by ann26**
On pending page:
screenshot from 2017-08-11 09-25-52

Organisation details page:
screenshot from 2017-08-11 09-26-18
screenshot from 2017-08-11 09-27-32
screenshot from 2017-08-11 09-27-46
screenshot from 2017-08-11 09-28-00

Course details page:
screenshot from 2017-08-11 09-29-06
screenshot from 2017-08-11 09-29-17

### CODE REVIEW

**Comment by timlinux** [comment]
Hi Anita - its nice to see you are taking initiative here! I think though it will be better if you make the change of color on hover only and leave it monochrome in non hover state. If you look at your screenshots, your eye is drawn very strongly to the red blocks instead of the information. I think the red (and blue in your other buttons) is a nice visual queue when you are about to perform the action but should not be getting the user's focus in other cases.

**Comment by ann26** [comment]
@timlinux ok, I'll fix it

**Comment by ann26** [comment]
Hi @timlinux now the colours are showing only on hover, in non hover they are monochrome

**Comment by timlinux** [comment]
Lovely thanks @ann26

**Pull request merged**
