### PR TITLE
Checking translation timestamp

### PR DESCRIPTION
**Pull request by ismailsunni**
Sample result
screen shot 2018-03-05 at 20 59 25

First work, for worksheet model first. If it's approved, I will go to the other parts.

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM thanks @ismailsunni

**Comment by ismailsunni** [comment]
@Gustry added the unit test.

**Comment by ismailsunni** [comment]
More sample results:
screen shot 2018-03-08 at 11 01 10
screen shot 2018-03-08 at 11 01 28

**Comment by timlinux** [comment]
LGTM merge when ready thanks

**Pull request merged**
