### PR TITLE
update forms

### LINKED ISSUE #458: We need a way to set a template for an organisation
Did I miss it? It seems I cannot set a template for the organization certificates? Can you make a property for the organization editor that lets me upload the template. Having a sample template which demarcates where the logos etc will be placed also will be good.

I think we must fall back to having Petra and Christo prep the certificates for us?

### PR DESCRIPTION
**Pull request by ann26**
fix #458 

### we can upload background template of the certificate on the add new/edit course form:
screenshot from 2017-07-04 12-09-07
screenshot from 2017-07-04 12-09-18

### we can upload signature of the project's owner on the add new/update project form:
screenshot from 2017-07-04 12-06-16

### we can upload signature of the course convener on the add new/edit course convener form:
screenshot from 2017-07-04 12-09-45

### we can upload organisation logo on the add new/edit organisation form:
screenshot from 2017-07-04 12-07-41
screenshot from 2017-07-04 12-08-18
screenshot from 2017-07-04 12-08-29

### CODE REVIEW

**Comment by dimasciput** [comment]
@ann26 this looks odd, please fix this

27815919-46bb1bc8-60b2-11e7-8f8b-33218cf70efd_png_1_282x665_pixels

**Comment by ann26** [comment]
ok @dimasciput

**Comment by ann26** [comment]
Hi @dimasciput , now it is like this
screenshot from 2017-07-04 14-35-49

**Comment by timlinux** [comment]
@ann26 maybe just pull it left some more and remove the rectangle around the button and label?

Once you have done that please merge and deploy to staging for me to test.

Thanks!

**Comment by ann26** [comment]
@timlinux ok

**Comment by ann26** [comment]
update:
screenshot from 2017-07-05 08-48-04

**Pull request merged**
