### PR TITLE
Fix certification bar content display on landing page.

### LINKED ISSUE #653: Project landing page design changed
From the latest develop code, I realised that the Project landing page design changed a bit. 
Previously it was like this:
screenshot from 2017-12-20 17-06-13

Now it is like this:
screenshot from 2017-12-20 17-04-23

I think the latest design draws user attention more to the subheading instead of the actual content list, for example in the certification box. What do you think @timlinux ?

### PR DESCRIPTION
**Pull request by sonlinux**
Fix #653
 
screenshot from 2017-12-22 11-19-34

### CODE REVIEW

**Comment by ann26** [comment]
Maybe remove the line below the Heading text and make subheading font smaller?

**Comment by sonlinux** [comment]
>Maybe remove the line below the Heading text and make subheading font smaller?

Update @ann26, how is it now?

**Comment by ann26** [comment]
can you put the screenshot too please?

**Comment by ann26** [comment]
Maybe make the subheading font size (12pt?) the same with the items font size and reduce the margin between heading and subheading, something like this:
screenshot from 2017-12-22 16-39-44

**Comment by sonlinux** [comment]
>Maybe make the subheading font size: 12pt? and reduce the margin between heading and subheading, something like this:

Updated @ann26 

screenshot from 2017-12-22 11-59-20

**Comment by ann26** [comment]
LGTM

**Pull request merged**
