### PR TITLE
Changed title of side block from Releases (Changelog) to Release Changelogs

### PR DESCRIPTION
**Pull request by sonlinux**
see #579 

screenshot from 2017-10-10 19 02 16

### CODE REVIEW

**Comment by Gustry** [comment]
@sonlinux You should try to clean your working branch. In this PR (and also the previous one), you have some commits which don't belong to this PR. (look the `files changed` tab on this page).
Maybe try when you want to work on a new feature:
`git checkout develop`
`git reset --hard upstream/develop`
`git checkout -b new_branch_with_the_name_you_want`

Don't worry, GIT is little bit weird at the beginning to understand branch etc ;-)

**Comment by sonlinux** [comment]
Thanks a lot @Gustry :-) by telling me about such errands ill grow stronger and more smart :-) ill take not of that from now onwards :-)

**Comment by sonlinux** [comment]
*note :-)

**Comment by sonlinux** [comment]
@Gustry can I write test for changing html title? :-)

**Comment by timlinux** [comment]
@sonlinux so you will need to tidy up your PR to remove the extra stuff before we can apply it. No need for a test for this one....

**Comment by sonlinux** [comment]
Alright @timlinux am working on it.

**Pull request closed without merging**
