### PR TITLE
change logo size

### LINKED ISSUE #484: Certificate logos need to be rendered larger
screen shot 2017-07-31 at 9 02 22 am

Can you make the project and certifying organization logos bigger in the layout please? Maybe 2x vertical and horizontal?

### PR DESCRIPTION
**Pull request by ann26**
fix #484 

How about this @timlinux ?
screenshot from 2017-07-31 15-40-05

### CODE REVIEW

**Comment by timlinux** [comment]
Yeah that looks good thanks. Please make the tests pass then I will merge.

**Comment by ann26** [comment]
@timlinux I've been trying to tweak the travis.yml to have the test passed. But I think the problem is because the postgresql 3 in the new travis environment failed to create user, so some tests in `vota.tests.test_views` , `base.tests.test_views` and `changes.tests.test_views` are failing. Should I disable the test temporarily until I figure out how to fix this?

**Comment by ann26** [comment]
@timlinux the latest commit is using `dist: trusty` environment in travis and it is only testing `core` and `certification`

**Comment by timlinux** [comment]
@ann26 yeah testing again trusty if fine for me, thanks.

**Pull request merged**
