### PR TITLE
added download button on worksheet detail

### PR DESCRIPTION
**Pull request by sumandari**
Please see #1337 

image

### CODE REVIEW

**Comment by zacharlie** [comment]
Not sure if it matters whether the download data button should come before or after the PDF button. My thinking would be to move the download data button before the PDF button because not all lessons include sample data and it may remain a bit more consistent. maybe @timlinux can advise.

**Comment by timlinux** [comment]
> Not sure if it matters whether the download data button should come before or after the PDF button. My thinking would be to move the download data button before the PDF button because not all lessons include sample data and it may remain a bit more consistent. maybe @timlinux can advise.

Yup that makes sense thanks - @sumandari will you do that? Will be great if you can get this deployed tomorrow @sumandari before training starts...

**Comment by dimasciput** [comment]
Hi @sumandari , can you use these icons for the download buttons
[download_icon.zip](https://github.com/kartoza/prj.app/files/6418603/download_icon.zip)

**Review by dimasciput — APPROVED** [review]
LGTM

**Comment by sumandari** [comment]
This fix has been deployed on changelog.kartoza.com and changelog.qgis.org version 2.1.5

**Comment by timlinux** [comment]
Thank you very much @sumandari !

**Pull request merged**
