### PR TITLE
Fix print certificate

### LINKED ISSUE #400: Generate certificate PDF
# Problem

Once a certificate is paid for this needs to be created as a PDF.

# Proposed Solution

Use Reportlab or similar to create the PDF.

### LINKED ISSUE #401: Add Print Certificate View
# Problem

Users want to have a view to request printing of certificates.

# Proposed Solution

Create an appropriate view.

### LINKED ISSUE #430: Print certificate does not work
e.g. http://staging.changelog.qgis.org/en/qgis/certifyingorganisation/test0/course/qgis_test_2017-06-06-2017-06-07/#
Clicking on the print button does nothing.

### PR DESCRIPTION
**Pull request by ann26**
fix #401, fix #400, and fix #430 

generated pdf (updated):
screenshot from 2017-06-23 13-38-24

peek 2017-06-22 16-45

you can change the background too:
screenshot from 2017-06-23 14-02-51

### CODE REVIEW

**Comment by ann26** [comment]
updated layout:
screenshot from 2017-06-23 16-14-04

**Comment by timlinux** [comment]
Lovely bubbly - I guess you need to apply the other pr #448 before this one? Can you resolve the merge conflicts then we can merge.

**Comment by ann26** [comment]
Hi @timlinux , it is ready to be merged now :) we don't need to apply other PR first.

**Comment by ann26** [comment]
Hi @timlinux this PR is ready to be merged, we don't need to merge other PR first :)

**Comment by Gustry** [comment]
Sorry I didn't see your demo, it looks nice !

Is-there a button to download a zip with all certificates inside?

**Comment by ann26** [comment]
Hi @Gustry , it's okay, thanks! :)
No, you can only download one certificate at a time.

**Comment by Gustry** [comment]
Ok, so maybe it's one of the next feature: to download and print in bulk all certificates ;-)

**Comment by ann26** [comment]
@Gustry yeah, I think it's a good idea :)

**Comment by timlinux** [comment]
Oh sorry I merged some of your others first as I didn't see your message @ann26 


Merging now....

**Pull request merged**
