### PR TITLE
Added changelog-managers to project model

### PR DESCRIPTION
**Pull request by timlinux**
WIP do not merge

### CODE REVIEW

**Comment by ann26** [comment]
hi @timlinux 
I made a PR to continue this PR here https://github.com/timlinux/projecta/pull/1

**Comment by ann26** [comment]
hi @timlinux I fixed the migrations here https://github.com/timlinux/projecta/pull/2 (in this commit https://github.com/timlinux/projecta/pull/2/commits/42cf8e844e4634bb420a292be2324164eaaa591b).

**Comment by timlinux** [comment]
Can you check the test issues @ann26 ?

**Comment by ann26** [comment]
@timlinux the issues in the test is migrations conflict, I fixed the migrations here https://github.com/timlinux/projecta/pull/2

**Comment by timlinux** [comment]
Thanks @ann26 !

**Comment by timlinux** [comment]
Thanks so much @ann26

**Pull request merged**
