### PR TITLE
Show example layout for a CSV file.

### LINKED ISSUE #753: We should add info template to upload csv file
User may not know the template of csv file that should be uploaded for attendee list.
Maybe we should add the example template view somewhere in this page
screenshot from 2018-02-07 11-33-30

### PR DESCRIPTION
**Pull request by sonlinux**
Fix #753 

I have added a screen layout of an example view for the csv that we expect to be uploaded.

csv_example

### CODE REVIEW

**Comment by timlinux** [comment]
Please fix:

* An example look ... to say rather "Format for the file to be uploaded:"
* Indicate whether the header row is needed in the CSV file
^ The upload button is floating around in the middle of nowhere, please align it better (e.g. pull to bottom alignment with the table and left flush with browse button)

**Comment by sonlinux** [comment]
Thanks @timlinux 
Will do so.

**Comment by sonlinux** [comment]
Updated @timlinux 

csv_clean

**Comment by sonlinux** [comment]
HI @Gustry 
Can we have this work merged?
Thanks

**Comment by timlinux** [comment]
Looks good @sonlinux ! LGTM

**Pull request merged**
