### PR TITLE
add sponsorship amount paid

### LINKED ISSUE #220: Sponsorship period should also include the amount sponsored for that period
It could be that the sponsor gives more than the minimum amount for that sponsorship level, so we should also record the exact amount given.

### PR DESCRIPTION
**Pull request by ann26**
fix #220

form:
screenshot from 2017-09-22 15-16-55
screenshot from 2017-09-22 15-17-08

sponsor list:
the amount sponsored is displayed when it is available.
screenshot from 2017-09-22 15-15-52

sponsorship period details:
when the amount sponsored is available:
screenshot from 2017-09-22 15-16-04

when the amount sponsored is not available:
screenshot from 2017-09-22 15-16-14

sponsor details: amount sponsored is displayed when it is available.
screenshot from 2017-09-22 15-45-54

### CODE REVIEW

**Comment by timlinux** [comment]
@andreasneumann could you review this?

**Comment by timlinux** [comment]
@ann26 I think we must just go ahead and merge this - we can tweak again if @andreasneumann has any further comments

**Comment by andreasneumann** [comment]
Looks ok to me. Thanks a lot!

Would this also be used in the automatically generated invoice?

**Comment by andreasneumann** [comment]
Separate currency also makes sense, because in some cases sponsor want to pay in their local currency.

However, € should be the default currency. >90% of our sponsors us this currency.

**Comment by ann26** [comment]
Hi @andreasneumann I added the default currency value (EUR) to the model

**Comment by timlinux** [comment]
@andreasneumann wrote:

> Would this also be used in the automatically generated invoice?

I think we can do that - @ann26 can you work with @jeanabdesmidt to get https://github.com/kartoza/projecta/pull/272 merged then we should be able to do the full workflow for manual sponsorship management. When stripe support comes, we can automate the whole process...

**Comment by ann26** [comment]
@timlinux will do

**Pull request merged**
