### PR TITLE
GitHub - Parse the content to find the "funded by" and its URL

### PR DESCRIPTION
**Pull request by Gustry**
In a pull request, I'm trying to parse and find the funder when harvesting the PR.

For instance : https://github.com/3liz/lizmap-web-client/pull/1823

Funded by XXX URL

I just did that with my unittest, I will try to give it a try on my local.

CC @zacharlie @sumandari @timlinux

### CODE REVIEW

**Comment by timlinux** [comment]
Awesome, thanks @Gustry - @zacharlie will you make sure to document this in the wiki  and also write to the dev list explaining how to get their fundner parsed out for their PRs (maybe add it to the PR template too?)

**Comment by timlinux** [comment]
LGTM

**Comment by Gustry** [comment]
It might be fragile, but better than nothing ;-)

These strings should work (according to unittest) : 
```
* Funded by Teddy BEAR https://teddy.bear
* Funded by Teddy
funded by Teddy
```

**Comment by timlinux** [comment]
@Gustry can you rebase please?

**Comment by Gustry** [comment]
Gentle ping the Kartoza team ;-)

Let us know when it's deployed on changelog.kartoza.com

**Review by dimasciput — APPROVED** [review]
Thanks @Gustry !

**Pull request merged**
