### PR TITLE
download certificates as a zip

### PR DESCRIPTION
**Pull request by ann26**
Download all issued certificates in one course as one zip file

In course details page:
screenshot from 2017-08-10 11-55-39

When the download button is clicked, user can save/view the zip file:
screenshot from 2017-08-10 12-00-15

The zip file contains folder with course name and all issued certificates is inside that folder:
screenshot from 2017-08-10 12-03-40

### CODE REVIEW

**Comment by timlinux** [comment]
Very nice thanks - can you just address the comments in #495 and then we can apply this.

**Comment by ann26** [comment]
sure @timlinux :)

**Comment by ann26** [comment]
Hi @timlinux here's the update:

normal view:
screenshot from 2017-08-16 16-11-23

when hover:
screenshot from 2017-08-16 16-11-43

**Comment by timlinux** [comment]
Thanks - please merge when conflicts are resolved

**Comment by ann26** [comment]
ok @timlinux

**Pull request merged**
