### PR TITLE
Sponsor, sponsorship levels and periods

### PR DESCRIPTION
**Pull request by rischanlab**
Hi @timlinux 

This PR is for issues #169 until #173 except the user permission. (I made it one because it has relation)
As I told before in comment that I put the sponsorship levels and periods in the nav bar. 

screen shot 2015-12-28 at 6 01 11 pm

After user add the project. First he need to add `sponsorship level`. 

screen shot 2015-12-28 at 9 12 01 pm

This is the view of sponsorship level lists. 

screen shot 2015-12-28 at 4 43 34 pm

Then, user have to add `sponsorship periods`

screen shot 2015-12-28 at 9 12 30 pm

And this is the view of `sponsorship periods` list

screen shot 2015-12-28 at 4 43 56 pm

After that, now he can add `Sponsor`

screen shot 2015-12-28 at 5 13 57 pm

screen shot 2015-12-28 at 9 19 23 pm

This is the view of sponsor list

screen shot 2015-12-28 at 5 57 53 pm

and how about the renewed sponsor @timlinux ?
In previous I put it in the sponsor list page (beside of `create new sponsor menu`)

screen shot 2015-12-28 at 9 16 52 pm

And also for the project owner I still have no idea, I'll do it later. 
Thanks.

### CODE REVIEW

**Comment by timlinux** [comment]
> This is the view of sponsorship level lists.

Please sort in descending order with according to sponsorship value for this view.

> Then, user have to add sponsorship periods

Ok this is still not correct so the schema should be:

screen shot 2015-12-29 at 00 55 44

**Projects**

* One project can have many sponsors
* One project can have many sponsorship periods

**Sponsors**

* One sponsor can have many sponsorship periods

**Sponsorship Periods**

* Each sponsorship period has one sponsor
* Each sponsorship period has one sponsorship level (the financial value should be duplicated into the sponsorship period in case the sponsorship level value changes over time)

**Sponsorship levels**

* Each sponsorship level has zero or more sonship periods associated with it


Its coming on nicely, thanks @rischanlab CC @pcavallini

**Comment by rischanlab** [comment]
Hi @timlinux 
before I commit  and push my changes I have little bit confused. 

I guess I am understand the purpose of sponsorship period, we can input multiple period with same sponsor and level, so we don't need renewed sponsorship. 

This is the screenshoot of sponsorship period

screen shot 2015-12-29 at 8 23 10 pm

To input the sponsorship period user need to fill `sponsor` and `sponsorship level` so before user want to input `sponsorship period` he must input `sponsor` and `sponsorship level` first. is that correct?

screen shot 2015-12-29 at 8 23 36 pm

screen shot 2015-12-29 at 8 23 50 pm

So, my question is how about `sponsor` form? 
in this case the sponsor form is just like this. 

screen shot 2015-12-29 at 8 24 24 pm

And also the list of sponsor will be weird because without period. But we can move the current and past sponsor in the `sponsorship period` page.

**Comment by timlinux** [comment]
Hi @rischanlab 

Looking at your screenshots, everything looks fine now. We will just need two special views:

* **<project>/sponsors/current** - lists all currently active sponsors, grouped by sponsorship level
* **<project>/sponsors/past** - lists all historical sponsors, grouped by sponsorship  level

Note that for past view the same sponsor could appear multiple times for the different years they have sponsored e.g. company **foo** sponsored bronze in 2011, silver in 2012, silver in 2013 etc.

The current sponsors view will be also embedded in the version view underneath the version description.

I hope that makes sense?

- [ ] Can you please move the sponsor and sponsor level fields so that they appear first in the sponsorship period form?

- [ ] Also there should probably be some validation to prevent overlapping periods for the same project by the same sponsor

Thanks!

**Comment by timlinux** [comment]
@rischanlab anything else you have on your todo list here? I'd like to merge it. Can you fix the two flake errors?

**Comment by rischanlab** [comment]
OK @timlinux wait a minutes, I forget to fixing the flake8.

**Comment by timlinux** [comment]
Thanks very much @rischanlab !

**Pull request merged**
