### PR TITLE
add sponsorship programme

### LINKED ISSUE #219: Sponsors page should provide outbound link to project sponsors page
And also a text field where the project sponsorship programme can be described in detail.

These should be stored as properties of the project model.

### PR DESCRIPTION
**Pull request by ann26**
fix #219 

Button to view sponsorship programme in a project:
when user is logged in
screenshot from 2017-10-11 17-46-10
when user is not logged in
screenshot from 2017-10-11 17-47-35

### Sponsorship programme page
When empty
For staff user and project owner:
screenshot from 2017-10-11 17-43-02

for other users:
screenshot from 2017-10-11 17-57-05

When is not empty
for staff user and project owner
screenshot from 2017-10-11 17-46-52

for other users:
screenshot from 2017-10-11 17-46-21

### form
screenshot from 2017-10-11 17-44-08
screenshot from 2017-10-11 17-44-28
screenshot from 2017-10-11 17-44-57
screenshot from 2017-10-11 17-45-32
screenshot from 2017-10-11 17-45-42

### CODE REVIEW

**Comment by timlinux** [comment]
Hi @ann26 sorry if my original ticket was not well described - does your change make the icon / net of a sponsor name a clickable link that takes you to their web site if the sponsor URL was populated?

Currently in develop it just opens the sponsor logo large:

licecap

**Comment by ann26** [comment]
Not yet, but I can make it like that.

**Comment by ann26** [comment]
@timlinux the icon now will take you to their website when sponsor url is populated.

peek 2017-10-12 09-26

**Comment by timlinux** [comment]
LGTM thanks @ann26

**Pull request merged**
