### PR TITLE
Change font to Lato

### PR DESCRIPTION
**Pull request by dimasciput**
Hi @timlinux 

I was thinking projecta current font is not that good, so I try to changed it with Lato font ( https://fonts.google.com/specimen/Lato ) 

Old font
old

New font 
new

What do you think?

### CODE REVIEW

**Comment by timlinux** [comment]
I'm going to go with "I'll trust your judgement's this one' since I can't see too much difference between the two screenies. Looks good to me!

**Comment by timlinux** [comment]
LGTM

**Comment by dimasciput** [comment]
LGTM

**Comment by dimasciput** [comment]
@timlinux I can't seems to merge it because of lgtm pending approval?

**Comment by dimasciput** [comment]
LGTM

**Comment by dimasciput** [comment]
LGTM

**Comment by timlinux** [comment]
LGTM

**Comment by timlinux** [comment]
I think maybe I need to tweak the maintainers list in for LGTM to work right....

**Pull request merged**
