### PR TITLE
GitHub PR parser : add more checks in the regexp

### PR DESCRIPTION
**Pull request by Gustry**
* More token
* With separator `:`

@sumandari It's ok to merge, covered by tests.

### CODE REVIEW

**Comment by sumandari** [comment]
Thank you @Gustry, could you please fix the test so that it gives the green tick?

**Comment by Gustry** [comment]
Done @sumandari

**Review by sumandari — APPROVED** [review]

**Comment by sumandari** [comment]
Thank you @Gustry!
I will merge it now.

**Comment by linfiniti** [comment]
Thanks Sumandari. Will you take a server snapshot then deploy it?

**Comment by sumandari** [comment]
Hi @linfiniti, this commit has been deployed on https://changelog.qgis.org. (version 2.1.3)

**Pull request merged**
