### PR TITLE
Create tool to generate invalid FurtherReading link (in progress)

### LINKED ISSUE #1326: worksheet links can become stale or unavailable and should be manually fixed
# Problem

All lessons have further reading sections where we put links. When the links become unavailable the reading section becomes stale.

# Solution

I suggest a little tool or script that basically generates all invalid links in a PDF/text file like

```
The following links are unavailable
https://changelog.qgis.org/en/qgis/lesson/symbology-22/detail/81/?q=3.1 has invalid links or unavailable links:
* http://foo.bar.txt
```
Or just saying
```
The following sections have invalid links
https://changelog.qgis.org/en/qgis/lesson/symbology-22/detail/81/?q=3.1
https://changelog.qgis.org/en/qgis/lesson/symbology-22/detail/167/?q=3.3
```

This tool can be run per need and should ideally be visible to the lessons manager.

Use case:
Before each training session, we run the tool and manually fix the links in the respective sections

### PR DESCRIPTION
**Pull request by sumandari**
This PR fixes #1326.

- [x] Create class to generate invalid Further Reading link
- [x] Write unit test
- [x] Display on frontend
- [x] save the output

/cc @NyakudyaA

### CODE REVIEW

**Comment by sumandari** [comment]
### click on the `check invalid link` button


image
---
### checking the invalid link

image

---
### result with anchor element
image


---

changelog_1326

**Comment by sumandari** [comment]
changelog_1326

**Comment by NyakudyaA** [comment]
Thanks, @sumandari, Can you save that output to PDF or any format.

**Comment by sumandari** [comment]
Alright @NyakudyaA, I will create the function to save the output.

**Comment by sumandari** [comment]
### Add the download button in modal:

invalid_further_link

---
### PDF result

invalid_further_link_pdf

**Comment by NyakudyaA** [comment]
Can we get this merged @sumandari

**Comment by sumandari** [comment]
some changes haven't covered  by unit test. will added it with another ticket.

**Pull request merged**
