### PR TITLE
Add interface to create a team

### LINKED ISSUE #307: No way to make a team
We need the same create etc paradigm as versions has for teams:

screen shot 2016-06-22 at 00 05 21

Should look like a variation of this with a project logo, list of teams and create etc tools for teams:

screen shot 2016-06-22 at 00 05 59

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #307

### CODE REVIEW

**Comment by timlinux** [comment]
Thanks @dimasciput 

Could I make two small requests:

* Can you get into the habit of adding tests when we fix things / add features?
* When you make a pull request, would you mind including screenshots to accompany the description - it makes it easy to see what has been done and when looking back through the PR history, it gives and easy way to see what changed.

Thanks!

**Comment by timlinux** [comment]
BTW Same request to @rischanlab and myself!

**Comment by dimasciput** [comment]
@timlinux well noted, thanks!

**Comment by dimasciput** [comment]
@timlinux 

Addressing this issue #311 : 
- Removed committee ballots from the menu and make it a submenu of team rather
- Removed start ballot from the menu and make it a submenu of team rather
- After creating a new team, redirect the user to /en/committees/

**Pull request merged**
