### PR TITLE
Removed bold from fonts in sponsers and changelog side blocks.

### PR DESCRIPTION
**Pull request by sonlinux**
See #578 

screenshot from 2017-10-10 18 41 29

### CODE REVIEW

**Comment by timlinux** [comment]
Are you working in a separate branch? You seem to have changes from your other PR mixed in.

**Comment by sonlinux** [comment]
Yes I was working from issue generated branch in pycharm, but I realised I had git mixed up of changes. @Gustry advised on the possible git commands that can help  avoid such occurances.

**Comment by sonlinux** [comment]
Is there a way I can fix these pushed commits that are not supposed to be in this branch @timlinux ?

**Comment by Gustry** [comment]
Many ways to do that. Maybe the easiest way to do that is a cherry-pick.
```
git fetch upstream
git checkout develop
git reset --hard upstream/develop
git checkout -b remove_bold
git cherry-pick COMMIT_ID, you need to do that for every commit needed in you PR
git push remove_bold
```
and then create a new PR based on that new branch

**Comment by sonlinux** [comment]
Many thanks @Gustry , am doing that.

**Pull request closed without merging**
