### PR TITLE
update ui

### LINKED ISSUE #437: fix design layout

### PR DESCRIPTION
**Pull request by ann26**
fix #437 

### Organisation details page:
screenshot from 2017-07-03 14-07-13
screenshot from 2017-07-03 13-51-41
screenshot from 2017-07-03 13-51-59
screenshot from 2017-07-03 13-52-16

### Training Center details page:
screenshot from 2017-07-03 13-58-40
screenshot from 2017-07-03 13-58-53

### Course Type details page:
screenshot from 2017-07-03 13-52-39

### Course details page:
screenshot from 2017-07-03 13-53-13
screenshot from 2017-07-03 13-53-32

### datepicker on create/update course:
screenshot from 2017-07-03 13-29-28

### CODE REVIEW

**Comment by dimasciput** [comment]
Looking good. @ann26 can you try to open the datepicker in safari, because sometimes there is an issue in safari. Or maybe you can try this datepicker instead, http://t1m0n.name/air-datepicker/. It will works on every browser.

**Comment by timlinux** [comment]
Also would be good if you can use a more consistent style for the various tables (make them match more the little infographic boxes here:

screen shot 2017-07-03 at 7 21 32 pm

@ann26 can you resolve the merge conflicts please?

**Comment by ann26** [comment]
@dimasciput ok I'll check it, thanks.

@timlinux ok will do

**Comment by ann26** [comment]
#  Update:
### datepicker: using air-datepicker
screenshot from 2017-07-04 09-31-43

### organisation details:
screenshot from 2017-07-04 11-01-15
screenshot from 2017-07-04 11-01-30
screenshot from 2017-07-04 11-02-06
screenshot from 2017-07-04 11-02-21

**Pull request merged**
