### PR TITLE
Check the GitHub token if using the GitHub API

### PR DESCRIPTION
**Pull request by Gustry**
Maybe a solution to #1215 I'm not sure.

@timlinux

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM

**Comment by timlinux** [comment]
@sumandari can you look why the tests are failing so we can merge this?

**Comment by sumandari** [comment]
@timlinux the following test Class are inheriting the wrong class. Instead of `factory.DjangoModelFactory`, they supposed to be `factory.django.DjangoModelFactory` 

- https://github.com/kartoza/prj.app/blob/develop/django_project/core/model_factories.py#L13
- https://github.com/kartoza/prj.app/blob/develop/django_project/vota/tests/model_factories.py#L10
- https://github.com/kartoza/prj.app/blob/develop/django_project/vota/tests/model_factories.py#L30
- https://github.com/kartoza/prj.app/blob/develop/django_project/vota/tests/model_factories.py#L56

**Comment by sumandari** [comment]
@timlinux I have submitted PR for fixing the test https://github.com/kartoza/prj.app/pull/1221

**Comment by Gustry** [comment]
I can rebase after the merge of the other PR if needed.

**Comment by timlinux** [comment]
@Gustry can you rebase please?

**Comment by Gustry** [comment]
There is nothing to rebase, it's already up to date with develop.
What is failing is codecov, not travis.

**Comment by dimasciput** [comment]
thanks @Gustry

**Review by dimasciput — APPROVED** [review]

**Pull request merged**
