### PR TITLE
Added link to the certification platform description.

### LINKED ISSUE #728: Add link to explanation certification system on certificate
we should have a link to the text mentioned in #727 on the certificate

### PR DESCRIPTION
**Pull request by sonlinux**
Fix #728 

Added a link to certification system on the verify certificate page as per comments in the ticket.

updated_cert_link

### CODE REVIEW

**Comment by timlinux** [comment]
@sonlinux can you change last row in that table from:

Certification system: (i)

to

A single centered entry under the table reading "Read more about the certication system."

Thanks

**Comment by sonlinux** [comment]
Alright @timlinux doing that now

**Comment by sonlinux** [comment]
Updated code @timlinux

**Comment by timlinux** [comment]
Perfect LGTM thanks @sonlinux

**Pull request merged**
