### PR TITLE
Add right sidebar in version detail

### PR DESCRIPTION
**Pull request by dimasciput**
## Changes

Add sidebar for better navigation in version detail view

ezgif-1334934565

### CODE REVIEW

**Comment by dimasciput** [comment]
Needs djanggo collectstatic, I don't know if it counts as Docker build.

**Comment by dimasciput** [comment]
Added 'Get Permalink' button 
Fix for https://github.com/kartoza/projecta/issues/372
permalink-button
screenshot from 2016-07-28 15 28 32

**Comment by dimasciput** [comment]
@timlinux What do you think about this?

**Comment by timlinux** [comment]
Beauuuuuuuutiful! I love it. LGTM

**Pull request merged**
