### PR TITLE
add flatpage

### PR DESCRIPTION
**Pull request by anitanh**
This PR:
 - Added flatpage non project, where will be added to the dropdown on the main project listing view, as follows:
Screenshot from 2020-03-22 20-11-06
To add/delete/edit pages for this one can be done in this admin:
Screenshot from 2020-03-22 20-07-30

- Added flatpage for each project which will be to the dropdown on the main project dashboard view as follows:
Screenshot from 2020-03-22 20-11-21
To add/delete/edit pages for this one can be done in this admin:
Screenshot from 2020-03-22 20-07-40

- content for the flatpage is html friendly meaning you can input the same as if you write in the html

What do you think @timlinux ?

### CODE REVIEW

**Comment by timlinux** [comment]
I need to have a play with it... Is it deployed on staging?

**Comment by ann26** [comment]
@timlinux not yet, I will deploy this to staging

**Comment by timlinux** [comment]
Thanks @ann26 I had a play, it works great. Can you deploy to production and to changelog.qgis.org  (backing up both first).

**Comment by ann26** [comment]
@timlinux deployed to changelog.qgis.org, I will deploy to production after merging the django2.2 branch to develop and master

**Pull request merged**
