### PR TITLE
Suppport svg and webp formats for sustaining member logos

### PR DESCRIPTION
**Pull request by sumandari**
This PR refers to #1278

### CODE REVIEW

**Comment by sumandari** [comment]
{% thumbnail %} fails to load svg, so that it wont display the image

---
svg

changelog_1279_svg

image


---
webp

changelog_1279_webp

image

**Comment by sumandari** [comment]
enable debug to display thumbnail errors

```
THUMBNAIL_DEBUG = True
```

image

**Comment by timlinux** [comment]
LGTM, please make tests pass for future PRs

**Comment by timlinux** [comment]
cc @andreasneumann

**Comment by andreasneumann** [comment]
Looking forward to use more svg and webp files in the future ;-)

Thanks!

**Pull request merged**
