### PR TITLE
include 'http' to permalink

### LINKED ISSUE #627: Permalink is missing the HTTP protocol
screen shot 2017-10-30 at 08 41 15

The HTTP protocol is missing from the permalink. So when we copy/paste, it creates a link not clickable like this:
changelog.qgis.org/en/qgis/version/3.0.0/#remove-trusted-status-from-plugin-manager

### PR DESCRIPTION
**Pull request by sonlinux**
Fix  #627 

screenshot from 2017-12-22 14-06-24

### CODE REVIEW

**Comment by Gustry** [comment]
@sonlinux This file is plain HTML, I don't think you need concatenation in that case.

**Comment by sonlinux** [comment]
>@sonlinux This file is plain HTML, I don't think you need the '+' concatenation operator in that case. I think it should be exactly like the # on the same line.

Updated @Gustry

**Comment by Gustry** [comment]
Sorry, I have another comment.
In the `request` documentation of django, there is `scheme`, it will give you the correct protocol used for the request (ftp, http, ...) . It will even switch between `https` or `http` if needed/available for an HTTP request.
So you should use the `request.scheme` property. Try it and tell me if it works.

Then for Travis, I will let @ann26 check for that

**Comment by Gustry** [comment]
There is also `get_raw_uri` will should do all of them in one call before the slug

**Comment by ann26** [comment]
hi @Gustry and @sonlinux , maybe travis updated its environment? I ran travis in the branch that previously passed the test and now it is failed :(

**Comment by sonlinux** [comment]
>Sorry, I have another comment.
In the request documentation of django, there is scheme, it will give you the correct protocol used for the request (ftp, http, ...) . It will even switch between https or http if needed/available for an HTTP request.
So you should use the request.scheme property. Try it and tell me if it works.

Hi @Gustry, 
the ```request.scheme``` property works fine.

**Comment by sonlinux** [comment]
Hi @Gustry 
Please take a another review on this PR when you can.
Thanks

**Comment by sonlinux** [comment]
thanks @Gustry 
But we need to fix travis environment before merge.

**Comment by Gustry** [comment]
The problem is already in develop: https://github.com/kartoza/projecta/commits/develop so it's fine IMHO

**Comment by sonlinux** [comment]
Alright, ill go ahead and merge,

**Pull request merged**
