### PR TITLE
Certificates should be cached

### LINKED ISSUE #506: Certificates should be cached once they are created
# Problem

Currently we re-generate the certs each time the view is called. Besides taking a while to generate, we have the issue that if the project detail or course details are subsequently changed, the content of the certificate can change and it may no longer reflect the original intent of the certificate. 

# Proposed Solution

So rather lets cache the certificate in the media folder (so it gets backed up etc). and have a button on the course view that optionally lets the organization manager re-render the certificates if needed.

### PR DESCRIPTION
**Pull request by jeanabdesmidt**
fix #506 

Certificates are now generated once, stored in /media/pdf/<certificateid>.pdf and served from there.

### CODE REVIEW

**Comment by timlinux** [comment]
@jeanabdesmidt please pay attention to PEP8 / pylint compliance - see the details in Travis - it will tell you which lines were at fault and what the error was. e.g.

```
....................../django_project/certification/views/certificate.py:19:1: E302 expected 2 blank lines, found 1
./django_project/certification/views/certificate.py:208:5: E265 block comment should start with '# '
./django_project/certification/views/certificate.py:209:5: E265 block comment should start with '# '
./django_project/certification/views/certificate.py:210:5: E265 block comment should start with '# '
./django_project/certification/views/certificate.py:210:80: E501 line too long (94 > 79 characters)
./django_project/certification/views/certificate.py:229:47: E231 missing whitespace after ','
./django_project/certification/views/certificate.py:245:80: E501 line too long (80 > 79 characters)
./django_project/certification/views/certificate.py:317:80: E501 line too long (80 > 79 characters)
./django_project/certification/views/certificate.py:343:80: E501 line too long (80 > 79 characters)
./django_project/certification/views/certificate.py:350:80: E501 line too long (82 > 79 characters)
./django_project/certification/views/certificate.py:365:47: E231 missing whitespace after ','
```

**Comment by jeanabdesmidt** [comment]
Fixed #513

**Comment by ann26** [comment]
Hi @jeanabdesmidt , I was wondering why did you close this PR?

**Comment by jeanabdesmidt** [comment]
@ann26 it was closed automatically when I reported the fix.

**Comment by ann26** [comment]
@jeanabdesmidt ah okay, also you can add `fix <issue number>` at the top of this PR so this PR will look attached to the issue you are working on

**Pull request merged**
