### PR TITLE
Dynamic table header and displaying notes/description

### PR DESCRIPTION
**Pull request by sumandari**
This PR refers to #1241 and #847. It does:
- change the static requirement header table element into a dynamic value
- display note/description on printed material

---
web view

1241_web

---
PDF output

1241_pdf

---
Edit worksheet detail

1241_edit

---
Edit specification detail 

1241_edit1

### CODE REVIEW

**Comment by zacharlie** [comment]
I think this is great 👍 , but I am a bit concerned about the labels of "notes" and "description". Both seem to perform the same function, but are applied to different columns. I would advocate that they be labelled **"Title Notes"** and **"Value Notes"**.

I don't know how important this is to change in the back-end. Personally I feel like just changing the form labels should be sufficient for now, as long as the function of these fields (and the labelling conventions) is properly documented so that other developers/ administrators might make more sense of this.

**Comment by timlinux** [comment]
LGTM once @zacharlie 's comments factored in

**Comment by sumandari** [comment]
Hi @zacharlie, I updated the PR:
- rename notes and description to title_notes and value_notes
- remove css styling for value_notes and title_notes so that it will have the same font-size with the title and the value as per @timlinux feedback.
  
image

image

**Review by zacharlie — APPROVED** [review]
LGTM

**Pull request merged**
